feed/urls.py
from django.urls import path
from .views import IndexView, PostCreateView, PostDeleteView, PostDetailView, PostExploreView

app_name = "feed"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("explore/", PostExploreView.as_view(), name="explore"),
    path("<int:pk>/", PostDetailView.as_view(), name="view"),
    path("post/", PostCreateView.as_view(), name="post"),
    path("delete/<int:pk>/", PostDeleteView.as_view(), name="delete"),
]

til/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from feed import urls as feed_urls
from user import urls as user_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("user/", include(user_urls, namespace="user")),
    re_path("", include("allauth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from .views import ProfileDeleteView, ProfileDetailView, FollowView, ProfileNameUpdateView, ProfileUsernameUpdateView

app_name = "user"

urlpatterns = [
    path("<str:username>/", ProfileDetailView.as_view(), name="profile"),
    path("<str:username>/follow/", FollowView.as_view(), name="follow"),
    path("delete/<str:username>/", ProfileDeleteView.as_view(), name="delete"),
    path("update-name/<str:username>/", ProfileNameUpdateView.as_view(), name="update-name"),
    path("update-username/<str:username>/", ProfileUsernameUpdateView.as_view(), name="update-username"),
]

feed/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    content = models.TextField(max_length=280)
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateModified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

til/templates/components/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'build.css' %}">
	<style>*, pre {font-family: 'Inter', sans-serif;}</style>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Noto+Serif&family=Noto+Serif+Display:wght@500;600&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body class="bg-slate-900 selection:bg-white selection:text-rose-900">
	<header>
		{% include "./header.html" %}
	</header>
	
  <main>
		{% block body %}
			{% if messages %}
				<div>
					<strong>Messages:</strong>
					<ul>
						{% for message in messages %}
						<li>{{message}}</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			
			{% comment %} side bar navigation {% endcomment %}
			{% include "./navbar.html" %}
		
				<div class="px-28 hidden lg:block"></div>

				{% block content %}{% endblock content %}
			</div>

		{% endblock body %}
	</main>
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="{% static 'main.js' %}"></script>
</body>
</html>

til/templates/components/card.html
<article class="group bg-pink-700 text-white flex flex-col items-start ring ring-transparent hover:ring-white rounded-xl">
  <section class="w-full pointer-events-none">
    <section class="w-full p-3 pl-4 pb-0 flex flex-wrap font-medium text-sm">
      <a href="{% url 'user:profile' post.author %}" class="pointer-events-auto">
        <span class="mr-1 hover:underline">
          {% if post.author.first_name or post.author.last_name %}
            {{post.author.first_name}} {{post.author.last_name}}{% else %}{{post.author.username}}{% endif %}</span>
        <span class="text-gray-100 font-light mr-2">@{{post.author}}</span>
      </a>
      <time class="text-gray-100"><span class="hidden md:inline">-&nbsp;&nbsp;</span>{{post.dateCreated}}</time>
    </section>
  </section>
  <a href="{% url 'feed:view' post.id %}" class="hover:bg-gray-50/10 rounded-b-xl block w-full p-8 pt-2 {% if view %}pb-16{% else %}pb-3{% endif %}">
    <h1 class="block w-full leading-tight {% if view %}text-3xl{% else %}text-xl{% endif %} font-semibold mb-4 drop-shadow-[0_0_1px_rgba(16,16,16,0.5)]">
      <pre class="break-all whitespace-pre-wrap">{{post.content}}</pre>
    </h1>
  </a>
</article>

til/templates/components/header.html
<nav class="w-full text-zinc-300 fixed z-[1000] p-2 bg-slate-900/80 backdrop-blur-xl flex items-center px-4">
  <button id="menuBtn" class="text-3xl px-4 inline-block lg:hidden bi bi-list" aria-label="Toggle navigation"></button>
  <div class="flex-grow text-3xl font-extrabold text-pink-600 px-4" aria-label="Today I Learned">
    T<span class="text-zinc-300">·</span>I<span class="text-zinc-300">·</span>L
  </div>
  {% if request.user.is_anonymous %}
    <a href="{% url 'account_login' %}" class="text-lg rounded-xl flex justify-start items-center">
      <span class="text-2xl bi bi-plus-lg"></span>
      <span class="pl-2">Post</span>
    </a>
  {% else %}
    <button id="navPostBtn" class="text-lg px-3 rounded-xl flex justify-start items-center {% if post_active %} font-bold bg-pink-700{% endif %}">
      <span class="text-2xl bi bi-plus-lg"></span>
      <span class="pl-3">Post</span>
    </button>
  {% endif %}
</nav>

til/templates/components/modal.html
<div class="w-full h-screen absolute top-0 flex justify-center bg-black/50 z-50 invisible">
  <form id="js-create-post-form">
    {% csrf_token %}
    <textarea name="content" id="id_content" maxlength="280" required></textarea>
    <button type="submit">Post</button>
  </form>  
</div>

til/templates/components/navbar.html
<div class="flex flex-row justify-between items-start">
<nav class="text-zinc-300 bg-slate-900/80 backdrop-blur-xl h-full flex flex-col gap-2 mt-[3.28rem] p-4 fixed -ml-56 lg:-ml-0 transition-all ease-out md:fixed lg:fixed lg:flex z-50 js-navbar">
  <a href="{% url 'feed:index' %}" class="text-lg py-3 pl-3 pr-20 rounded-xl flex justify-start items-center">
    <span class="text-2xl bi bi-house"></span>
    <span class="pl-3{% if home_active %} font-bold{% endif %}">Home</span>
  </a>
  <a href="{% url 'feed:explore' %}" class="text-lg py-3 pl-3 pr-20 rounded-xl flex justify-start items-center">
    <span class="text-2xl bi bi-hash"></span>
    <span class="pl-3{% if explore_active %} font-bold{% endif %}">Explore</span>
  </a>

  {% if request.user.is_authenticated %}
    <a href="{% url 'user:profile' request.user.username %}" class="text-lg py-3 pl-3 pr-20 rounded-xl flex justify-start items-center">
      <span class="text-2xl bi bi-person"></span>
      <span class="pl-3 {% if profile_active %} font-bold{% endif %}">Profile</span>
    </a>
    <a href="{% url 'account_logout' %}" class="text-lg py-3 pl-3 pr-20 rounded-xl flex justify-start items-center">
      <span class="text-2xl bi bi-box-arrow-left"></span>
      <span class="pl-3">Logout</span>
    </a>
  {% else %}
    <a href="{% url 'account_login' %}" class="text-lg py-3 pl-3 pr-20 rounded-xl flex justify-start items-center">
      <span class="text-2xl bi bi-shield-lock"></span>
    <span class="pl-3">Login</span></a>
  {% endif %}
</nav>

til/templates/components/post-form.html
{% if request.user.is_authenticated %}
  <form id="js-create-post-form" class="hidden mb-3">
    <div class="flex flex-col gap-3 p-3 bg-slate-800 rounded-xl">
      {% csrf_token %}
      <textarea name="content" id="id_content" class="text-xl text-white bg-transparent border-2 border-zinc-300 outline-2 outline-pink-700 max-h-80 min-h-[14rem] p-4 rounded-xl" maxlength="280" placeholder="What did you learn today?" required></textarea>
      <div>
        <span class="text-zinc-400 inline-block py-2"><span id="contentLength">0</span>/280</span>
        <button type="submit" class="text-white font-semibold float-right py-2 px-12 rounded-xl bg-pink-700 disabled:opacity-50" disabled>Post</button>
      </div>
    </div>
  </form>
{% endif %}