feed/urls.py
from django.urls import path
from .views import IndexView, PostCreateView, PostDeleteView, PostDetailView, PostExploreView

app_name = "feed"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("explore/", PostExploreView.as_view(), name="explore"),
    path("<int:pk>/", PostDetailView.as_view(), name="view"),
    path("post/", PostCreateView.as_view(), name="post"),
    path("delete/<int:pk>/", PostDeleteView.as_view(), name="delete"),
]

til/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from feed import urls as feed_urls
from user import urls as user_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("user/", include(user_urls, namespace="user")),
    re_path("", include("allauth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from .views import ProfileDeleteView, ProfileDetailView, FollowView, ProfileNameUpdateView, ProfileUsernameUpdateView

app_name = "user"

urlpatterns = [
    path("<str:username>/", ProfileDetailView.as_view(), name="profile"),
    path("<str:username>/follow/", FollowView.as_view(), name="follow"),
    path("delete/<str:username>/", ProfileDeleteView.as_view(), name="delete"),
    path("update-name/<str:username>/", ProfileNameUpdateView.as_view(), name="update-name"),
    path("update-username/<str:username>/", ProfileUsernameUpdateView.as_view(), name="update-username"),
]

feed/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    content = models.TextField(max_length=280)
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateModified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

til/templates/explore.html
{% extends "./components/base.html" %}

{% block title %}Explore posts | Today · I · Learned{% endblock %}

{% block content %}

  <div class="p-3 flex flex-col mt-12">
    
    {% include "./components/post-form.html" %}

    <div class="flex flex-col gap-3 js-post-container">
      {% for post in posts %}
        {% include "./components/card.html" with post=post %}
      {% empty %}
        No posts yet
      {% endfor %}
    </div>
  </div>

  {% comment %} {% include "./components/modal.html" %} {% endcomment %}
{% endblock content %}

til/templates/index.html
{% extends "./components/base.html" %}

{% block title %}Today · I · Learned{% endblock title %}

{% block content %}
<div class="w-full p-3 flex flex-col mt-12">
	{% if request.user.is_authenticated %}
	<form id="js-create-post-form" class="hidden mb-3">
		<div class="flex flex-col gap-3 p-3 bg-slate-800 rounded-xl">
			{% csrf_token %}
			<textarea name="content" id="id_content" class="text-xl text-white bg-transparent border-2 border-zinc-300 outline-2 outline-pink-700 max-h-80 min-h-[14rem] p-4 rounded-xl" maxlength="280" placeholder="What did you learn today?" required></textarea>
			<div>
				<span class="text-zinc-400 inline-block py-2"><span id="contentLength">0</span>/280</span>
				<button type="submit" class="text-white font-semibold float-right py-2 px-12 rounded-xl bg-pink-700 disabled:opacity-50" disabled>Post</button>
			</div>
		</div>
	</form>
	{% endif %}

	<div class="flex flex-col gap-3 js-post-container">
		{% for post in posts %}
			{% include "./components/card.html" with post=post %}
		{% empty %}
			No posts yet
		{% endfor %}
	</div>
</div>
{% endblock content %}

til/templates/post.html
<form action="." method="POST">
  {% csrf_token %}
  {{form}}
  <button type="submit">Post</button>
</form>

til/templates/profile.html
{% extends "./components/base.html" %}

{% block content %}
  {% comment %} {{profile.first_name}} {{profile.last_name}}
  <br><small>@{{profile.username}}</small>
  <br><br>
  Total posts: {{total_post_count}}
  <br>
  Following: {{total_following_count}}
  <br>
  Followers: {{total_follower_count}}
  <br><br>
  {% if request.user.is_anonymous %}
    <button type="button">Follow (Link to login)</button>
  {% else %}
    {% if show_follow_button %}
      <button type="button" class="js-follow" data-username={{profile.username}}
        data-action="{% if beingFollowed %}un{% endif %}follow" data-url="{% url 'user:follow' profile.username %}">
        {% if beingFollowed %}Unfollow{% else %}Follow{% endif %}
      </button>
    {% endif %}
  {% endif %}
  <br><br> {% endcomment %}
  <div class="w-full p-3 flex flex-col mt-12">
    {% include "./components/post-form.html" %}

    <div class="bg-pink-700 p-16 rounded-xl">
      <h1 class="text-4xl text-white font-bold">
        {% if profile.first_name or profile.last_name %}
        {{profile.first_name}} {{profile.last_name}}{% else %}{{profile.username}}{% endif %}
      </h1>
      <h2>@{{profile.username}}</h2>
      <div class="float-right">
        {% if request.user.is_anonymous %}
        <button type="button" class="marker:p-3 border-2 rounded-xl text-white">Follow (Link to login)</button>
      {% else %}
        {% if show_follow_button %}
          <button type="button" class="p-3 border-2 rounded-xl text-white js-follow" data-username={{profile.username}}
            data-action="{% if beingFollowed %}un{% endif %}follow" data-url="{% url 'user:follow' profile.username %}">
            {% if beingFollowed %}Unfollow{% else %}Follow{% endif %}
          </button>
        {% endif %}
      {% endif %}
      </div>
    </div>
    
    <div class="p-3 text-white text-xl font-medium">
      {{total_post_count}} Posts
      &nbsp;&nbsp;&nbsp;<b>·</b>&nbsp;&nbsp;&nbsp;
      {% if total_follower_count %}{{total_follower_count}} Followers{% endif %}
      &nbsp;&nbsp;&nbsp;<b>·</b>&nbsp;&nbsp;&nbsp;
      {% if total_following_count %}Following {{total_following_count}}{% endif %}
    </div>

    <hr>

    {% if request.user.is_authenticated and request.user.username == profile.username %}
      <div class="flex justify-around items-center gap-4 flex-wrap">
        <form action="{% url 'user:update-name' request.user %}" method="POST" class="mt-8 flex flex-col justify-center gap-3 flex-wrap">
          {% csrf_token %}
          <p class="text-xl text-white font-medium pb-2">Update name</p>
          <input type="text" class="p-3 bg-transparent border-2 outline-2 outline-pink-700 text-white text-xl rounded-xl" name="first_name" id="id_first_name" value={{profile.first_name}}>
          <input type="text" class="p-3 bg-transparent border-2 outline-2 outline-pink-700 text-white text-xl rounded-xl" name="last_name" id="id_last_name" value={{profile.last_name}}>
          <button type="submit" class="p-3 bg-pink-700 rounded-xl">Update Name</button>
        </form>

        <form action="{% url 'user:update-username' request.user %}" method="post" class="flex flex-col gap-3 flex-wrap">
          {% csrf_token %}
          <p class="text-xl text-white font-medium pb-2">Update username</p>
          <input type="text" class="p-3 bg-transparent border-2 outline-2 outline-pink-700 text-white text-xl rounded-xl" name="username" id="id_username" value={{profile.username}}>
          <button type="submit" class="p-3 bg-pink-700 rounded-xl">Update Username</button>
        </form>
      </div>
      <br><br><hr><br>
      <form action="{% url 'user:delete' request.user %}" method="POST" class="mt-4 flex flex-wrap justify-between items-center gap-3">
        <a href="{% url 'account_change_password' %}" class="font-medium py-3 px-6 rounded-xl text-white bg-yellow-600">Change Password</a>
        {% csrf_token %}
        <div class="flex flex-wrap justify-end items-center gap-3">
          <p class="text-yellow-500 py-3">This action cannot be undone!</p>
          <button type="submit" class="font-medium py-3 px-6 rounded-xl text-white bg-red-700 bi bi-trash-fill" value="DELETE"><span class="pl-3">Delete my account</span></button>
        </div>
      </form>
    {% endif %}
    <br><br><br>

    {% comment %} <h1>{% if request.user.username == profile.username %}Your{% else %}{{profile.username}}'s{% endif %} posts...</h1>
    <div class="flex flex-col gap-3 js-post-container">
      {% for post in posts %}
        {% include "./components/card.html" with post=post %}
      {% empty %}
        No posts yet
      {% endfor %}
    </div> {% endcomment %}
  </div>
{% endblock content %}

til/templates/view.html
{% extends "./components/base.html" %}

{% block title %}
	Today I learned {{post.content}} from {{post.author.first_name}} {{post.author.last_name}} (@{{post.author}})
{% endblock title %}

{% block content %}
	<div class="w-full p-3 flex flex-col mt-12">
		{% if request.user.is_authenticated %}
		<form id="js-create-post-form" class="hidden mb-3">
			<div class="flex flex-col gap-3 p-3 bg-slate-800 rounded-xl">
				{% csrf_token %}
				<textarea name="content" id="id_content" class="text-xl text-white bg-transparent border-2 border-zinc-300 outline-2 outline-pink-700 max-h-80 min-h-[14rem] p-4 rounded-xl" maxlength="280" placeholder="What did you learn today?" required></textarea>
				<div>
					<span class="text-zinc-400 inline-block py-2"><span id="contentLength">0</span>/280</span>
					<button type="submit" class="text-white font-semibold float-right py-2 px-12 rounded-xl bg-pink-700 disabled:opacity-50" disabled>Post</button>
				</div>
			</div>
		</form>
		{% endif %}

		<div class="flex flex-col gap-3 js-post-container">
			{% include "./components/card.html" with post=post view=True %}
			{% if request.user.is_authenticated and request.user == post.author %}
				<form action="{% url 'feed:delete' post.id %}" method="POST">
					{% csrf_token %}
					<button type="submit" value="DELETE">Delete this post</button>
				</form>
			{% endif %}
		</div>
	</div>
{% endblock content %}